In [1]:
from plotly_calplot import calplot
import pandas as pd
import nbformat
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np

In [2]:
# ディレクトリをここに設定
%cd /Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/access_data

/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/access_data

# 地図を描こう
### アクセスされているけど，まだ緯度経度を登録していない地域を検出

In [3]:
df = pd.read_csv("../access_data/ユーザー属性の詳細_地域.csv", encoding="shift-jis")
df = df[df["蝨ｰ蝓"] != "(not set)"]
df = df[df["蟶ょ玄逕ｺ譚"] != "(not set)"]

# 都市名と県名の情報を作成
df["都市名"] = df["蝨ｰ蝓"] + "," + df["蟶ょ玄逕ｺ譚"]
df

,蝨ｰ蝓,蟶ょ玄逕ｺ譚,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ,譁ｰ隕上Θ繝ｼ繧ｶ繝ｼ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ縺ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝育紫,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝医ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰｼ1 繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧奇ｼ,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧翫ｮ蟷ｳ蝮お繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝域凾髢,繧､繝吶Φ繝域焚,繧ｭ繝ｼ繧､繝吶Φ繝,繝ｦ繝ｼ繧ｶ繝ｼ 繧ｭ繝ｼ繧､繝吶Φ繝育紫,蜷郁ｨ亥庶逶,都市名
2,Tokyo,Shinjuku City,146,135,54,0.341772,0.369863,14.095890,570,0,0,0,"Tokyo,Shinjuku City"
3,Miyagi,Sendai,133,130,356,0.732510,2.676692,141.105263,4245,0,0,0,"Miyagi,Sendai"
4,Osaka,Osaka,79,73,33,0.383721,0.417722,10.848101,333,0,0,0,"Osaka,Osaka"
5,Tokyo,Shibuya,63,60,28,0.388889,0.444444,18.761905,302,0,0,0,"Tokyo,Shibuya"
6,Tokyo,Minato City,44,38,20,0.416667,0.454545,22.909091,234,0,0,0,"Tokyo,Minato City"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Yamagata,Tsuruoka,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Yamagata,Tsuruoka"
274,Zurich,Zurich,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Zurich,Zurich"
275,Guangdong Province,Guangzhou,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Guangdong Province,Guangzhou"
276,Hokkaido,Asahikawa,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Hokkaido,Asahikawa"
277,Ontario,Toronto,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Ontario,Toronto"

In [14]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# 1回だけ作る
geolocator = Nominatim(user_agent="myGeocoder", timeout=10)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)

for index, row in df.iterrows():
    location = geocode(row["都市名"])

    if location:
        df.at[index, "緯度"] = location.latitude
        df.at[index, "経度"] = location.longitude
    else:
        df.at[index, "緯度"] = None
        df.at[index, "経度"] = None

    print(f"Processing {index+1}/{len(df)}: {row['都市名']}")

KeyError: '都市名'

In [5]:
df

,蝨ｰ蝓,蟶ょ玄逕ｺ譚,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ,譁ｰ隕上Θ繝ｼ繧ｶ繝ｼ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ縺ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝育紫,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝医ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰｼ1 繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧奇ｼ,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧翫ｮ蟷ｳ蝮お繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝域凾髢,繧､繝吶Φ繝域焚,繧ｭ繝ｼ繧､繝吶Φ繝,繝ｦ繝ｼ繧ｶ繝ｼ 繧ｭ繝ｼ繧､繝吶Φ繝育紫,蜷郁ｨ亥庶逶,都市名,緯度,経度
2,Tokyo,Shinjuku City,146,135,54,0.341772,0.369863,14.095890,570,0,0,0,"Tokyo,Shinjuku City",35.693860,139.703447
3,Miyagi,Sendai,133,130,356,0.732510,2.676692,141.105263,4245,0,0,0,"Miyagi,Sendai",38.267755,140.869150
4,Osaka,Osaka,79,73,33,0.383721,0.417722,10.848101,333,0,0,0,"Osaka,Osaka",34.693757,135.501454
5,Tokyo,Shibuya,63,60,28,0.388889,0.444444,18.761905,302,0,0,0,"Tokyo,Shibuya",35.663371,139.696495
6,Tokyo,Minato City,44,38,20,0.416667,0.454545,22.909091,234,0,0,0,"Tokyo,Minato City",35.654842,139.760987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Yamagata,Tsuruoka,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Yamagata,Tsuruoka",38.727219,139.826629
274,Zurich,Zurich,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Zurich,Zurich",47.374449,8.541042
275,Guangdong Province,Guangzhou,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Guangdong Province,Guangzhou",23.128845,113.259006
276,Hokkaido,Asahikawa,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Hokkaido,Asahikawa",43.770625,142.364974
277,Ontario,Toronto,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Ontario,Toronto",43.653482,-79.383935

In [13]:
df["freq"] = df['繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ']

fig = px.scatter_mapbox(
    df,
    lat='緯度',  # 緯度
    lon='経度',  # 経度
    size='freq',
    zoom=4,
    size_max=20,
    color_discrete_sequence=["#00d5ff"]
)

fig.update_layout(
    title_font_size=20,
    geo=dict(
        showcountries=True,  # 国境を表示
        showcoastlines=True,  # 海岸線を表示
        coastlinecolor="Grey",
        landcolor="LightYellow"
    ),
    mapbox_style='carto-darkmatter',
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        x=1,  # 凡例を右に移動
        y=1,  # 凡例を上に移動
        xanchor="right",  # 凡例の右端を基準に配置
        yanchor="top",  # 凡例の上端を基準に配置
        bgcolor="rgba(255, 255, 255, 0.7)",  # 背景を半透明の白に設定
        bordercolor="Black",  # 枠線の色
        borderwidth=1  # 枠線の幅
    ),
    # mapの初期表示の中心を日本に
    mapbox=dict(
        center=dict(lat=38.5548, lon=137.1529),  # 日本の緯度と経度
    )
)

fig.show()

KeyError: '繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ'

In [7]:
fig.write_html("/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/html_figures/access_map.html")

# github風のタイルplot

In [16]:
df = pd.read_csv("../access_data/レポートのスナップショット.csv", encoding="shift-jis")
df["Date"] = pd.to_datetime(df["N 譌･逶ｮ"])
df["log_user"] = df["繧｢繧ｯ繝ゑｿｽｿｽ 繝ｦ繝ｼ繧ｶ繝ｼ"].map(lambda x: np.log(x + 1))
df = df[df["Date"] >= "2024-11-19"]
df

         N 譌･逶ｮ  繧｢繧ｯ繝ゑｿｽｿｽ 繝ｦ繝ｼ繧ｶ繝ｼ       Date  log_user
49   2024/11/19                    0 2024-11-19  0.000000
50   2024/11/20                    0 2024-11-20  0.000000
51   2024/11/21                    0 2024-11-21  0.000000
52   2024/11/22                    0 2024-11-22  0.000000
53   2024/11/23                    0 2024-11-23  0.000000
..          ...                  ...        ...       ...
522    2026/3/7                    3 2026-03-07  1.386294
523    2026/3/8                   22 2026-03-08  3.135494
524    2026/3/9                    5 2026-03-09  1.791759
525   2026/3/10                    8 2026-03-10  2.197225
526   2026/3/11                    0 2026-03-11  0.000000

[478 rows x 4 columns]

In [17]:
fig = calplot(df, x='Date', y="log_user", colorscale='Blues')

# 背景色を黒、見やすいように文字色を白に指定
fig.update_layout(
    paper_bgcolor='#3f3f3f',  # 図全体の周りの背景色
    plot_bgcolor='#3f3f3f',   # プロットエリア（グラフ描画部）の背景色
    font=dict(color='white') # 文字色
)

fig.show()

In [18]:
fig.write_html("/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/html_figures/access_heatmap.html")